name: NodeJS with Grunt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Expo CLI
      # You may pin to the exact commit or the version.
      # uses: expo/expo-github-action@55b9dc47a87321cd1ab69fb49c879f41dc837d9d
      uses: expo/expo-github-action@3.0.0

    - name: Build
      run: |
        npm install -g expo-cli
        expo install
        expo start
